nome = input('Qual é o seu nome?')
print(nome)
idade = input('Qual é a sua idade?')
print(idade)
endereco = input('Qual é o seu endereço?')
print(endereco)
peso = input('Quantos quilos você pesa?')
print(peso)

print(nome, idade, endereco, peso)
